title: Jamfantwo
initials: Jfw
description: A medieval fantasy world-building project.
keywords: medieval,fantasy,world,world-building
lang: en
url: "https://katoli-dev.github.io/Jamfantwo"
permalink: pretty

incremental: true

sass:
  style: compressed

defaults:
  - scope:
      path: "content"
    values:
      layout: "default"

exclude:
  - "opencode.json"
  - ".opencode"
  - ".github"
  - "scripts"
  - "temp"

authors:
  - Contributors
